### ISSUE TITLE
Type for trait 3.23.1 says categorial instead of categorical

### ISSUE THREAD

**Issue by elchudi** [BioGeoMacro/GIFT#10]
Type for trait 3.23.1 says categorial instead of categorical when fetched with
trait_meta <- GIFT_traits_meta()

**Comment by pierredenelle** [comment]
Thanks for your comment, we have now fixed it for the beta version (GIFT_traits_meta(GIFT_version = "beta")), and it will be fixed from GIFT version 3.3 on when we push the next update (in the coming weeks).
