### ISSUE TITLE
What is a "suitable polygon"? (aka, suit_geo = TRUE)

### ISSUE THREAD

**Issue by Rekyt** [BioGeoMacro/GIFT#2]
Hey @patrickweigelt and @pierredenelle,
I'm opening this issue to make it probably more tractable to you, but tell me if you prefer emails.

I'm downloading checklists with `GIFT::GIFT_checklist()` and I realized there is the `suit_geo` argument. When I lookup in all the documentation of the package it only states "Is the polygon suitable?". But what it means is explained nowhere (including in the vignettes).
What are "suitable polygons" exactly?
I do see that it heavily influences the number of retrieved checklists:

``` r
all_suit_geo = GIFT::GIFT_checklist(
  taxon_name = "Tracheophyta",
  complete_taxon = FALSE,
  floristic_group = "all",
  complete_floristic = FALSE,
  geo_type = "All",
  list_set_only = TRUE,
  suit_geo = FALSE
)
#> Metadata for lists retrieved.
#> GIFT taxonomy downloaded.

only_suit_geo = GIFT::GIFT_checklist(
  taxon_name = "Tracheophyta",
  complete_taxon = FALSE,
  floristic_group = "all",
  complete_floristic = FALSE,
  geo_type = "All",
  list_set_only = TRUE,
  suit_geo = TRUE
)
#> Metadata for lists retrieved.
#> 
#> GIFT taxonomy downloaded.

# More lists with both suitable and non-suitable than with only suitable ones
nrow(all_suit_geo[[1]])
#> [1] 83623
nrow(only_suit_geo[[1]])
#> [1] 45968
```

<sup>Created on 2022-12-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by patrickweigelt** [comment]
Hi @Rekyt,
Thanks a lot for pointing this out. I think it is good to do this here. While the arguments taxon_name in combination with complete_taxon = TRUE and floristic_group in combination with complete_floristic = TRUE make sure that you only get back checklists for regions for which GIFT actually has lists aiming at covering both the entire taxonomic group and florsitic subset (for example native vascular plants), it does not mean that the checklists are necessarily complete (include all species). We therefore flagged regions in GIFT for which the combination of all checklists is obviously incomplete as suit_geo = 0. This has however only been done for native angiosperms and the assessment has been subjective. A more quantitative assessment of checklist completeness is pending. I will leave this issue open until we docuent the argument better.
Cheers,
Patrick
