### ISSUE TITLE
Timeout with big downloads

### ISSUE THREAD

**Issue by dylancraven** [BioGeoMacro/GIFT#5]
This is more of a suggestion than an issue, but I have found that increasing the timeout:
 `options(timeout` = max(1000, `getOption("timeout")))`

makes it easier to complete larger downloads.

**Comment by pierredenelle** [comment]
Hi Dylan,

many thanks for the suggestion, I will indicate this in the tutorials.
Not sure if I should code it in the functions though.

**Comment by dylancraven** [comment]
it would be more than sufficient in the tutorials.
