### ISSUE TITLE
API not wrking

### ISSUE THREAD

**Issue by spiritu-santi** [BioGeoMacro/GIFT#6]
I'm getting this error when trying to fetch data.
> GIFT_checklists()
Error in value[[3L]](cond) : 
  Either the API is wrongly specified or the server is down.

**Comment by pierredenelle** [comment]
Hi,
the code should work, maybe the server is overloaded at the moment because many people are trying the package now (the associated paper got published today) ;)

Alternatively, you can increase the timeout to ease larger downloads.:
options(timeout = max(1000, getOption("timeout")))

Best
