### ISSUE TITLE
Error in readBin when trying to get traits data

### ISSUE THREAD

**Issue by alittlevixen** [BioGeoMacro/GIFT#9]
Hello, 

I try to get data from the GIFT_traits function, as described in the Get Started tutorial, but it seems to have a bug. 

I can't generate the first object (generated by the following code : _height <- [GIFT_traits](https://biogeomacro.github.io/GIFT/reference/GIFT_traits.html)(trait_IDs = [c](https://rdrr.io/r/base/c.html)("1.6.2"), agreement = 0.66,
                      bias_ref = FALSE, bias_deriv = FALSE)_)

Here, I get this error : 

Error in readBin(3L, raw(0), 32768L) : cannot read from connection
In addition: Warning message:
In readBin(3L, raw(0), 32768L) :
  URL 'https://gift.uni-goettingen.de/api/extended/index3.1.php?query=species&startat=200000': Timeout of 60 seconds was reached

How can I fix it ? Is it because of a bug in the API key ? Or is it because of the quality of my internet connection ? 

Thank you in advance for you help

**Comment by profkarani** [comment]
Hello @alittlevixen,

I had the same issue lately. It could be an issue with internet connectivity and speed of download, so, I'm not sure about 'fixing it'. However, I am able to download data without difficulties after adjusting the timeout session from 60seconds to 300seconds.

> options(timeout = max(300, getOption("timeout")))

Hope it works for you too.

Thanks,

Anthony

**Comment by pierredenelle** [comment]
We added a side-note in the beginning of the main vignette with this workaround.
